### ISSUE TITLE
MPI error on linux

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II/edrixs#96] opened 2020-09-02 23:42 UTC
We have a strange MPI-related error arising inside a conda install of edrixs. Before we address it I am going to get the Linux version and get the user to work out whether it occurs in a separate environment without edrixs. 

![image](https://user-images.githubusercontent.com/699991/92046802-573d7200-ed51-11ea-9527-907047d972ff.png)

**Comment by leofang** [comment] 2020-09-02 23:49
1. Any chance this machine has a GPU?
2. What's the package info as returned by `conda list openmpi`?
3. Can you do `export OMPI_MCA_opal_cuda_support=0` and retry?

**Comment by mpmdean** [comment] 2020-09-02 23:54
Thanks a lot @leofang 

1. I will find out from the user
2. It's from a recent install from nsls2forge so very likely"
4.0.5
3. I'll ask the user to do this.

**Comment by leofang** [comment] 2020-09-02 23:57
OK. Please ask your user to also send you this info:
```
cat $CONDA_PREFIX/etc/openmpi-mca-params.conf
```

**Comment by leofang** [comment] 2020-09-02 23:58
btw how is mpi used in edrixs? Through mpi4py?

**Comment by mpmdean** [comment] 2020-09-03 00:06
Yes, via mpi4py and then underlying Fortran code bound with f2py.

**Comment by leofang** [comment] 2020-09-03 00:16
btw, taking a closer look at the screenshot, I noticed the MPI program is not launched with `mpirun -n N ... python ...`. Could be a problem here if Open MPI's daemon is not correctly set up, but I am not 100% sure.

**Comment by mpmdean** [comment] 2020-09-03 00:20
The user's machine does have GPUs. He is running this example

https://nsls-ii.github.io/edrixs/auto_examples/example_2_AIM_XAS.html#sphx-glr-auto-examples-example-2-aim-xas-py
which call our solver dependent on MPI here
https://github.com/NSLS-II/edrixs/blob/079cbe5d4eeddc0f513cb6c11391914660449fc1/edrixs/solvers.py#L1805

**Comment by mpmdean** [comment] 2020-09-03 15:08
All the MPI issues seem to have been solved via

```
export OMPI_MCA_opal_cuda_support=0
```

We still have an issue with the Fortran part of the code. 

[EDRIXSDebug9320.txt](https://github.com/NSLS-II/edrixs/files/5169460/EDRIXSDebug9320.txt)

**Comment by leofang** [comment] 2020-09-03 15:33
Thank you, @mpmdean! This is useful information for diagnosis. Looks like `$CONDA_PREFIX/etc/openmpi-mca-params.conf` is not honored for some reason. I can't reproduce this issue locally on a GPU machine, so something weird is going on.

A few follow-up questions:
1. If you do `unset OMPI_MCA_opal_cuda_support` to clear out the env var, and then run your program via `mpirun -n 1 python example_2_AIM_XAS.py`, would it give the same error as before? 
2. Now, with `OMPI_MCA_opal_cuda_support` unset, please run `mpirun -n 1 --mca mpi_show_mca_params 1 python example_2_AIM_XAS.py` and send me the output.
3. Set `export OMPI_MCA_opal_cuda_support=0`, rerun `mpirun -n 1 --mca mpi_show_mca_params 1 python example_2_AIM_XAS.py`, and send me the output.
4. What is the user's `conda --version`?

By the way, the `ImportError` for libopenblas seems to be due to some incompatibility between the build and run environment. It could be that when building the conda package it is linked to openblas, but the requirement is not exported to the run environment. It could also be that the user mixed up packages from default and conda-forge and nsls2forge (should be easy to check by inspecting the full output of `conda list`). I think NumPy from conda-forge is linked to openblas these days.

**Comment by leofang** [comment] 2020-09-03 15:39
FYI a bit of context for why we bother worrying about `OMPI_MCA_opal_cuda_support`: We now build Open MPI's CUDA awareness support by default, but we disable it by appending a few mca parameters to openmpi-mca-params.conf so that it would not interfere with normal usage (in CPU code), as otherwise Open MPI would attempt to load the CUDA driver (libcuda) at init time. For users who need CUDA support, they can then either set `OMPI_MCA_opal_cuda_support=1` or do `mpirun --mca opal_cuda_support 1 ...` to enable it. We've done this on both conda-forge and nsls2forge (I maintain the packages on both sides 😅) and this is the first compliant we receive, so I am particularly interested.

**Comment by mpmdean** [comment] 2020-09-03 21:51
@leofang Having had a chance to look at the users' computer, there appears to be an issue with the Fortan component of the edrixs conda package. I'm a bit unsure if there's an actual problem with MPI. I'd like to check with Maksim about this to be sure we're bugging the right thing before we return to looking at MPI, which might be okay.

**Comment by mrakitin** [comment] 2020-09-03 22:40
Hi @mpmdean, is the sequential version work?

I had an issue with testing `edrixs` while building it via a feedstock. In particular, `openmpi` was failing, but due to the missing `rsh` yum package (fixed by adding it here: https://github.com/nsls-ii-forge/edrixs-feedstock/blob/master/recipe/yum_requirements.txt, which propagated to the CI files). I don't think it's the cause here.

**Comment by mrakitin** [comment] 2020-09-03 22:42
We can add a problematic calculation as a test next to https://github.com/nsls-ii-forge/edrixs-feedstock/blob/5f8ff4bfef069596898f7fe0aaf7341288b18e75/recipe/meta.yaml#L44, so that it's tested every time we package a new version.

**Comment by mrakitin** [comment] 2020-09-03 22:46
> btw, taking a closer look at the screenshot, I noticed the MPI program is not launched with `mpirun -n N ... python ...`. Could be a problem here if Open MPI's daemon is not correctly set up, but I am not 100% sure.

I think in this case the code path should be different and should not invoke `mpi4py` inside. The test mentioned above has `mpirun/mpiexec` in the command to run the calculation.

**Comment by mrakitin** [comment] 2020-09-03 22:55
Just ran a build again, and it got openmpi 4.0.5. I see no issues with the test: https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=4521&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642.

Was the `example_2_AIM_XAS.py` example updated recently? That's what I have to use in tests: https://github.com/nsls-ii-forge/edrixs-feedstock/blob/master/recipe/example_2_AIM_XAS.py.

**Comment by mpmdean** [comment] 2020-09-03 22:55
Hi @mrakitin I found other seemingly deeper errors on the system throwing this problem:
https://github.com/nsls-ii-forge/edrixs-feedstock/issues/10

I'm stuck as to what is going on, but my feeling is that the issue raised there is deeper.

**Comment by mrakitin** [comment] 2020-09-03 23:34
I replied in the feedstock issue. I hope that helps.

**Comment by mpmdean** [comment] 2020-09-03 23:43
Thanks @mrakitin and @leofang 

I think the generic edrixs issue is solved by @mrakitin. I will see if the apparent MPI error still appears after edrixs is updated to build 2 of v 0.0.6

**Comment by leofang** [comment] 2020-09-04 09:03
> > btw, taking a closer look at the screenshot, I noticed the MPI program is not launched with `mpirun -n N ... python ...`. Could be a problem here if Open MPI's daemon is not correctly set up, but I am not 100% sure.
> 
> I think in this case the code path should be different and should not invoke `mpi4py` inside. The test mentioned above has both the sequential run and the run with `mpirun/mpiexec`.

If not launched with `mpirun`, the correctness of an MPI program is unpredictable. The best scenario is all MPI calls are no-op, but there is no guarantee since mpi4py is linked to Open MPI which requires `mpirun` to set up the runtime daemon. I still think we should check this, and don't immediately see how fixing the libopenblas issue discussed above (and in the other issue) would help. Keep me posted.

Another thing: I took a quick look at the problematic file `example_3_GS_analysis.py`, and I think it's strictly speaking unsafe to reload `example_2_AIM_XAS.py` as done here:
https://github.com/NSLS-II/edrixs/blob/8a63f8b077fa2212e34eab8f5f960c3ea20e6e66/examples/sphinx/example_3_GS_analysis.py#L21

The potential problem is not on the Python side but on the MPI side: Note that MPI is initialized by the time we do this:
https://github.com/NSLS-II/edrixs/blob/8a63f8b077fa2212e34eab8f5f960c3ea20e6e66/examples/sphinx/example_2_AIM_XAS.py#L36
and reloading this module would cause this line to be executed twice, but initializing MPI multiple times is not allowed by the standard AFAIK.

**Comment by mpmdean** [comment] 2020-09-04 22:51
So the blas issue is indeed solved. Regarding MPI

when executing as 
```
python example_2_AIM_XAS.py
```
we still see an error unless 
```
export OMPI_MCA_opal_cuda_support=0
```
is done.

I have asked the user to report if 
```
mpirun -n 1 python example_2_AIM_XAS.py
```
work correctly independently of ```export OMPI_MCA_opal_cuda_support=0```

I didn't appreciate what @leofang says about multiple MPI imports. I'll raise an issue regarding this point.

**Comment by mpmdean** [comment] 2020-09-08 16:50
We still seem to need to set ```export OMPI_MCA_opal_cuda_support=0```

otherwise we see an error as:
```
edrixs_env) [usrname@ip-0A322007 ~]$ mpirun -n 1 python example_2_AIM_XAS.py
--------------------------------------------------------------------------
An invalid value was supplied for an enum variable.

  Variable     : opal_cuda_support
  Value        : trueid
  Valid values : 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_register_params failed
  --> Returned value -18 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
```
The answers to @leofang 's questions are
1. No error after unsetting.
2. See Q2.txt (attached)
3. See Q3.txt (attached)
4. conda 4.8.4
[Q2.txt](https://github.com/NSLS-II/edrixs/files/5189690/Q2.txt)
[Q3.txt](https://github.com/NSLS-II/edrixs/files/5189691/Q3.txt)

**Comment by leofang** [comment] 2020-09-08 17:37
Hi @mpmdean I don't understand what you meant that you saw the error with `mpirun -n 1 python ...`. Your Q2.txt (with `OMPI_MCA_opal_cuda_support` unset) seems to run successfully to me. Note that in Q2.txt `opal_cuda_support` is set in `openmpi-mca-params.conf`, while in Q3.txt it's set by the env var, both as expected.

**Comment by mpmdean** [comment] 2020-09-08 21:16
Hi @leofang Not sure. If we want to debug this, we might try to videochat with the user?

**Comment by leofang** [comment] 2020-09-10 06:53
Let's give it one more shot. I locally tested this on a GPU machine and had no problem (no need to set any env var manually). Any chance your user could follow this? (i.e. create a new conda env and run the code)
```
conda create -n edrixs_test python=3.7 edrixs -c nsls2forge
conda activate edrixs_test
mpirun -n 1 python example_2_AIM_XAS.py
```

**Comment by mpmdean** [comment] 2020-09-10 19:27
@leofang  This is the report based on your suggested test

```
---------------------------------------------------------------------------------------------------------
(base) [usrname@ip- ~]$ conda activate edrixs_test
(edrixs_test) [usrname@ip- ~]$ mpirun -n 1 python example_2_AIM_XAS.py
--------------------------------------------------------------------------
An invalid value was supplied for an enum variable.

  Variable     : opal_cuda_support
  Value        : trueid
  Valid values : 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):
  opal_register_params failed
  --> Returned value -18 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
(edrixs_test) [usrname@ip-~]$
----------------------------------------------------------------------------------------------------------
```

**Closed** 2020-09-16 23:52 UTC

**Comment by mrakitin** [comment] 2020-09-17 01:27
What was the solution?

**Comment by mpmdean** [comment] 2020-09-17 13:54
Hi @mrakitin 

One needs to do
```
export OMPI_MCA_opal_cuda_support=0
```

ahead of running the code. (The other issue was a problematic conda package that's now solved.) In principle one maybe shouldn't have to run the export command, but it's not a big deal and it seems not to be generic to all GPU systems.

**Comment by mrakitin** [comment] 2020-09-17 13:58
Hi Mark, I see, thanks. One can prepend the env variable to the mpirun command if it's not desirable to set globally, such as
```py
OMPI_MCA_opal_cuda_support=0 mpirun ...
```

**Comment by leofang** [comment] 2020-09-17 16:47
As mentioned above, this usage is supported by Open MPI: `mpirun -n N --mca opal_cuda_support 0 ...` But I will open an issue upstream to keep this very strange bug tracked, and see if someone else could reproduce it.

**Comment by leofang** [comment] 2020-09-17 16:56
> But I will open an issue upstream to keep this very strange bug tracked, and see if someone else could reproduce it.

See https://github.com/conda-forge/openmpi-feedstock/issues/63.

**Comment by leofang** [comment] 2021-03-24 05:26
If this is still a issue, we need to check local Open MPI configs, see https://github.com/conda-forge/openmpi-feedstock/issues/63#issuecomment-735449707 and the links below.
